import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { prisma } from '../src/prisma';
import { requestAccountDeletion, processAccountDeletion, getDeletionReceipt, publicDeletionStatus, managedDeletionPath } from '../src/services/accountDeletion';
import { ensureNoUserBlock } from '../src/services/userBlock';
import { submitProfileReview, decideProfileReview } from '../src/services/profileReview';
import { isIosCommerceRequest } from '../src/middleware/iosCommerce';
import express from 'express';
import { authRequired } from '../src/middleware/auth';
import { signToken } from '../src/utils/jwt';
import { userBlockRouter } from '../src/routes/userBlock';
import { privacyRouter } from '../src/routes/privacy';
import { errorHandler } from '../src/middleware/error';

test('iOS commerce is identified independently of account; regular web remains available', () => {
  assert.equal(isIosCommerceRequest({ headers: { 'user-agent': 'Mozilla/5 CPUWebIOSApp/1.0' } }), true);
  assert.equal(isIosCommerceRequest({ headers: { 'x-cpu-client': 'ios' } }), true);
  assert.equal(isIosCommerceRequest({ headers: { 'user-agent': 'Mozilla/5 Safari' } }), false);
});
test('managed asset paths reject traversal', () => {
  assert.equal(managedDeletionPath('/uploads/avatars/2/a.png?v=1', 2), 'avatars/2/a.png');
  assert.equal(managedDeletionPath('/uploads/avatars/3/a.png', 2), null);
  assert.equal(managedDeletionPath('forum/../private'), null);
  assert.equal(managedDeletionPath('https://foreign.example/uploads/forum/a.png'), null);
});
test('account privacy lifecycle on isolated PostgreSQL', { skip: process.env.PRIVACY_INTEGRATION_TEST !== '1' }, async () => {
  const database = new URL(process.env.DATABASE_URL || 'http://invalid');
  assert.equal(database.hostname, '127.0.0.1');
  assert.equal(database.searchParams.get('schema'), 'privacy_test');
  const suffix = randomUUID();
  const app = express();
  app.use(express.json());
  app.use('/blocks', authRequired, userBlockRouter);
  app.use('/privacy', privacyRouter);
  app.use(errorHandler);
  const server = app.listen(0, '127.0.0.1');
  await new Promise<void>((resolve) => server.once('listening', resolve));
  const origin = `http://127.0.0.1:${(server.address() as any).port}`;
  try {
    const owner = await prisma.user.create({ data: { username: `privacy-${suffix}`, passwordHash: 'test', nickname: 'Original', bio: 'private', avatar: '/uploads/avatars/999/no.png' } });
    const other = await prisma.user.create({ data: { username: `other-${suffix}`, passwordHash: 'test', nickname: 'Other' } });
    const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${signToken({ userId: owner.id, studentId: owner.username, role: 'user', campus: '' })}` };
    assert.equal((await fetch(`${origin}/blocks`)).status, 401);
    await prisma.user.update({ where: { id: owner.id }, data: { avatar: `/uploads/avatars/${owner.id}/owned.png` } });
    const blocked = await fetch(`${origin}/blocks`, { method: 'POST', headers, body: JSON.stringify({ targetType: 'user', targetId: other.id }) });
    assert.equal(blocked.status, 200);
    const blockList = await (await fetch(`${origin}/blocks`, { headers })).json() as any;
    assert.equal(blockList.data.length, 1);
    assert.equal(blockList.data[0].targetId, undefined);
    await assert.rejects(ensureNoUserBlock(owner.id, other.id));
    await assert.rejects(ensureNoUserBlock(other.id, owner.id));
    await submitProfileReview(owner.id, { bio: 'pending biography' });
    let user = await prisma.user.findUniqueOrThrow({ where: { id: owner.id } });
    assert.equal(user.bio, 'private');
    assert.equal(user.profileReviewStatus, 'checking');
    await assert.rejects(decideProfileReview(owner.id, other.id, '{}', true, 'stale'));
    await decideProfileReview(owner.id, other.id, user.pendingProfile!, true, 'checked');
    user = await prisma.user.findUniqueOrThrow({ where: { id: owner.id } });
    assert.equal(user.bio, 'pending biography');
    const board = await prisma.board.create({ data: { slug: suffix, name: 'Test' } });
    const topic = await prisma.topic.create({ data: { boardId: board.id, authorId: owner.id, title: 'private title', content: 'private content' } });
    const untouched = await prisma.topic.create({ data: { boardId: board.id, authorId: other.id, title: 'keep', content: 'keep' } });
    const conversation = await prisma.directConversation.create({ data: { participantLowId: Math.min(owner.id, other.id), participantHighId: Math.max(owner.id, other.id), initiatedById: owner.id, lastMessageAt: new Date() } });
    await prisma.directMessage.create({ data: { conversationId: conversation.id, senderId: other.id, content: 'private reply' } });
    assert.equal((await fetch(`${origin}/privacy/account-deletion`, { method: 'POST', headers, body: JSON.stringify({ confirmation: 'wrong', acknowledged: true }) })).status, 400);
    const deletion = await fetch(`${origin}/privacy/account-deletion`, { method: 'POST', headers, body: JSON.stringify({ confirmation: '删除我的账户', acknowledged: true }) });
    assert.equal(deletion.status, 202);
    const result = (await deletion.json() as any).data;
    assert.equal((await fetch(`${origin}/blocks`, { headers })).status, 401);
    const receiptResponse = await fetch(`${origin}/privacy/account-deletion/status`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ receipt: result.receipt }) });
    assert.equal(receiptResponse.status, 200);
    assert.equal((await receiptResponse.json() as any).data.username, undefined);
    await assert.rejects(requestAccountDeletion(owner.id));
    assert.equal((await prisma.user.findUniqueOrThrow({ where: { id: owner.id } })).status, 'deleting');
    const media: string[] = [];
    let fail = true;
    let failCdn = false;
    const dependencies = { deleteMedia: async (path: string) => { media.push(path); }, deleteSessions: async () => {}, purgeMedia: async () => { if (failCdn) throw new Error('cache refresh pending'); }, deleteVoiceHub: async () => { if (fail) throw new Error('temporary outage'); } };
    await processAccountDeletion(result.id, dependencies);
    let job = await getDeletionReceipt(result.receipt);
    assert.equal(job.status, 'retry');
    assert.equal(job.phase, 'external');
    assert.equal(job.lastError, 'voicehub');
    assert.equal(job.completedAt, null);
    assert.ok(job.encryptedPayload && !job.encryptedPayload.includes(result.receipt));
    user = await prisma.user.findUniqueOrThrow({ where: { id: owner.id } });
    assert.equal(user.status, 'deleted'); assert.equal(user.bio, null); assert.equal(user.avatar, null);
    assert.ok(user.username.startsWith('deleted-'));
    assert.equal((await prisma.topic.findUniqueOrThrow({ where: { id: topic.id } })).content, '');
    assert.equal((await prisma.topic.findUniqueOrThrow({ where: { id: untouched.id } })).content, 'keep');
    assert.equal(await prisma.directMessage.count({ where: { conversationId: conversation.id } }), 0);
    assert.equal(await prisma.userBlock.count({ where: { ownerId: owner.id } }), 0);
    assert.ok(media.includes(`avatars/${owner.id}/owned.png`));
    fail = false;
    failCdn = true;
    await processAccountDeletion(result.id, dependencies);
    job = await getDeletionReceipt(result.receipt);
    assert.equal(job.status, 'retry'); assert.equal(job.lastError, 'cdn'); assert.equal(job.completedAt, null);
    failCdn = false;
    await processAccountDeletion(result.id, dependencies);
    job = await getDeletionReceipt(result.receipt);
    assert.equal(job.status, 'completed'); assert.equal(job.encryptedPayload, null);
    assert.ok(job.completedAt); assert.equal(publicDeletionStatus(job).status, 'completed');
    await processAccountDeletion(result.id, dependencies);
    assert.equal((await getDeletionReceipt(result.receipt)).attempts, 3);
    await assert.rejects(getDeletionReceipt('x'.repeat(43)));
  } finally { server.closeAllConnections(); await new Promise<void>((resolve) => server.close(() => resolve())); await prisma.$disconnect(); }
});
